/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

import Controller.InsereAluno;
import Model.Aluno;

/**
 *
 * @author josep
 */
public class CadAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadAluno
     */
    public CadAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ca_NomeAluno = new javax.swing.JTextField();
        ca_IdadeAluno = new javax.swing.JTextField();
        ca_CursoAluno = new javax.swing.JComboBox<>();
        ca_SerieAluno = new javax.swing.JComboBox<>();
        javax.swing.JButton ca_InserirDados = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ca_CPF = new javax.swing.JTextField();
        ca_Novo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ca_VoltarPrinc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do aluno:");

        jLabel2.setText("Idade do aluno:");

        jLabel3.setText("Curso do aluno:");

        jLabel4.setText("Série do aluno:");

        ca_NomeAluno.setToolTipText("");

        ca_IdadeAluno.setToolTipText("");

        ca_CursoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ADS", "Ciência da Computação", "GTI", "Jogos Digitais", "Sistema da Informação" }));

        ca_SerieAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Primeira", "Segunda", "Terceira", "Quarta", "Quinta", "Sexta", "Sétima", "Oitavo" }));
        ca_SerieAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_SerieAlunoActionPerformed(evt);
            }
        });

        ca_InserirDados.setText("Inserir");
        ca_InserirDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_InserirDadosActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CPF");
        jLabel7.setToolTipText("");

        ca_CPF.setToolTipText("");
        ca_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_CPFActionPerformed(evt);
            }
        });

        ca_Novo.setText("Novo");
        ca_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_NovoActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        ca_VoltarPrinc.setText("Voltar a Tela Principal");
        ca_VoltarPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_VoltarPrincActionPerformed(evt);
            }
        });
        jMenu1.add(ca_VoltarPrinc);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ca_NomeAluno)
                            .addComponent(ca_IdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ca_SerieAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ca_CursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ca_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(ca_InserirDados, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(ca_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca_NomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ca_IdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ca_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ca_CursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca_SerieAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca_InserirDados)
                    .addComponent(ca_Novo))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ca_VoltarPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_VoltarPrincActionPerformed
        // Voltar para Tela Principal
        TelaPrincipal nj = new TelaPrincipal();
        nj.setVisible(true);
        // Centraliza o frame no centro da tela
        nj.setLocationRelativeTo(null);   
        dispose(); // Fecha a janela

    }//GEN-LAST:event_ca_VoltarPrincActionPerformed

    private void ca_InserirDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_InserirDadosActionPerformed
        // Insere os dados no Banco de dados

        /*
        /Cria uma propriedade de mensagem de retorno
        /Essa propriedade recebe a mensagem e apresenta no
        /label ca_Mensagem
        */

        String mensagem = "";

        //Instancia o objeto alunos
        Aluno aluno = new Aluno();
        
        //Atribui os valores dos campos do formulário ao objeto aluno
        aluno.setNome(ca_NomeAluno.getText());
        aluno.setCpf(ca_CPF.getText());
        aluno.setIdade(Integer.parseInt(ca_IdadeAluno.getText()));
        aluno.setCurso(ca_CursoAluno.getSelectedItem().toString());
        aluno.setFase(ca_SerieAluno.getSelectedItem().toString());

        //Chama o método no Controller para inserir e validar os dados
       mensagem = InsereAluno.InsAluno(aluno);
        
       //Recebe a mensagem de retorno e apresenta em uma messagebox
        JOptionPane.showMessageDialog(null, mensagem, "Mensagem",
                JOptionPane.INFORMATION_MESSAGE);

        setVisible(true);           
        
        
    }//GEN-LAST:event_ca_InserirDadosActionPerformed

    private void ca_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ca_CPFActionPerformed

    private void ca_SerieAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_SerieAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ca_SerieAlunoActionPerformed

    private void ca_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_NovoActionPerformed
        // Prepara o forma para cadastrar um novo aluno

        // Limpas os objetos da interface para novo lançamento
        ca_NomeAluno.setText("");
        ca_CPF.setText("");
        ca_IdadeAluno.setText("");
        ca_CursoAluno.setSelectedIndex(0);
        ca_SerieAluno.setSelectedIndex(0);        
        
    }//GEN-LAST:event_ca_NovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ca_CPF;
    private javax.swing.JComboBox<String> ca_CursoAluno;
    private javax.swing.JTextField ca_IdadeAluno;
    private javax.swing.JTextField ca_NomeAluno;
    private javax.swing.JButton ca_Novo;
    private javax.swing.JComboBox<String> ca_SerieAluno;
    private javax.swing.JMenuItem ca_VoltarPrinc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
