/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.*;
import static javax.swing.JOptionPane.*;
import Data.Database;

/**
 *
 * @author josep
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tp_ButtonVadAluno = new javax.swing.JButton();
        tp_ButtonGerAlunos = new javax.swing.JButton();
        tp_ButtonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tp_CadAluno = new javax.swing.JMenuItem();
        tp_GerAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        tp_SairSist = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        tp_SobreSist = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Alunos.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        tp_ButtonVadAluno.setText("Abrir Cadastro de Aluno ");
        tp_ButtonVadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_ButtonVadAlunoActionPerformed(evt);
            }
        });

        tp_ButtonGerAlunos.setText("Abrir Gerenciador de Alunos");
        tp_ButtonGerAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_ButtonGerAlunosActionPerformed(evt);
            }
        });

        tp_ButtonSair.setText("Sair do Sistema");
        tp_ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_ButtonSairActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        tp_CadAluno.setText("Cadastro de Aluno");
        tp_CadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_CadAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(tp_CadAluno);

        tp_GerAluno.setText("Gerenciador de Alunos");
        tp_GerAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_GerAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(tp_GerAluno);
        jMenu1.add(jSeparator1);

        tp_SairSist.setText("Sair do Sistema");
        tp_SairSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_SairSistActionPerformed(evt);
            }
        });
        jMenu1.add(tp_SairSist);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        tp_SobreSist.setText("Sobre o Sistema");
        tp_SobreSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_SobreSistActionPerformed(evt);
            }
        });
        jMenu2.add(tp_SobreSist);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp_ButtonVadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tp_ButtonGerAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tp_ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(tp_ButtonVadAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp_ButtonGerAlunos)
                .addGap(130, 130, 130)
                .addComponent(tp_ButtonSair))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void tp_SairSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_SairSistActionPerformed
        // Finaliza o programa com código de saída 0 (sem erros)
        System.exit(0);  
    }//GEN-LAST:event_tp_SairSistActionPerformed

    private void tp_SobreSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_SobreSistActionPerformed
        // Dialogo que da informação sobre o sistema       
        JOptionPane.showMessageDialog(null, "Programa de cadastro de alunos \nExemplo de interface gráfica \ncom CRUD em Java.\n \n2024 - Material Didático" ,
                "Sobre o Programa", INFORMATION_MESSAGE);
    }//GEN-LAST:event_tp_SobreSistActionPerformed

    private void tp_ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_ButtonSairActionPerformed
        // Finaliza o programa com código de saída 0 (sem erros)
        System.exit(0);  
        
    }//GEN-LAST:event_tp_ButtonSairActionPerformed

    private void tp_ButtonVadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_ButtonVadAlunoActionPerformed
        // Abrir a Tela de Cadastro de Aluno
        CadAluno nj = new CadAluno();
        nj.setVisible(true);
        // Centraliza o frame no centro da tela
        nj.setLocationRelativeTo(null);    

        
    }//GEN-LAST:event_tp_ButtonVadAlunoActionPerformed

    private void tp_CadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_CadAlunoActionPerformed
        // Abrir a Tela de Cadastro de Aluno
        CadAluno nj = new CadAluno();
        nj.setVisible(true);
        // Centraliza o frame no centro da tela
        nj.setLocationRelativeTo(null);  
    }//GEN-LAST:event_tp_CadAlunoActionPerformed

    private void tp_ButtonGerAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_ButtonGerAlunosActionPerformed
        // Abre Gerenciador de alunos
         GerAluno nj = new GerAluno();
        nj.setVisible(true);
        // Centraliza o frame no centro da tela
        nj.setLocationRelativeTo(null);    

    }//GEN-LAST:event_tp_ButtonGerAlunosActionPerformed

    private void tp_GerAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_GerAlunoActionPerformed
       // Abre Gerenciador de alunos
        GerAluno nj = new GerAluno();
        nj.setVisible(true);
        // Centraliza o frame no centro da tela
        nj.setLocationRelativeTo(null);
    }//GEN-LAST:event_tp_GerAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton tp_ButtonGerAlunos;
    private javax.swing.JButton tp_ButtonSair;
    private javax.swing.JButton tp_ButtonVadAluno;
    private javax.swing.JMenuItem tp_CadAluno;
    private javax.swing.JMenuItem tp_GerAluno;
    private javax.swing.JMenuItem tp_SairSist;
    private javax.swing.JMenuItem tp_SobreSist;
    // End of variables declaration//GEN-END:variables
}
